version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rematricula_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rematricula_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: rematricula_api
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: rematricula_db
      JWT_SECRET: rematricula_super_secreta_123
      JWT_EXPIRES_IN: 1d
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
    ports:
      - '3000:3000'

volumes:
  pgdata: